apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name}}-deployment
  labels:
    app: {{  .Chart.Name}}
spec:
  replicas: {{  .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{  .Chart.Name}}
  template:
    metadata:
      labels:
        app:  {{  .Chart.Name}}
    spec:
      containers:
      - name: "{{  .Values.image.repository}}:{{  .Values.image.tag}}"
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "{{  .Values.resources.requests.memory}}"
            cpu: "{{  .Values.resources.requests.cpu}}"
          limits:
            memory: "{{  .Values.resources.limits.memory}}"
            cpu: "{{  .Values.resources.limits.memory}}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{  .Release.Name}}-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
