apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: #importing below resources
  - db-depl.yaml
  - db-service.yaml
  - db-config.yaml

commonLabels:   
  company: Bayer 

nameSuffix: - db