#stragegic merge is YAML appraoch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: my-app-container
          image: nginx:1.16.1
