apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubernetes resources to be managed by kustomize
resources:
  - db/
  - message-broker/
  - nginx/
#Customizations that need to be made
# # kubernetes resources to be managed by kustomize
# resources:
#   - db/db-config.yaml
#   - db/db-depl.yaml
#   - db/db-service.yaml
#   - message-broker/rabbitmq-config.yaml
#   - message-broker/rabbitmq-depl.yaml
#   - message-broker/rabbitmq-service.yaml
#   - nginx/nginx-depl.yaml
#   - nginx/nginx-service.yaml

commonLabels:
  department: Engineering 

namespace: debugging

namePrefix: Bayer-apac-


commonAnnotations:
  logging: verbose 